apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playwright-qa

resources:
  - namespace.yaml
  - ../../base

# Changed from 'patchesStrategicMerge' to 'patches'
patches:
  - path: patches/cronjob-schedules.yaml
  - path: patches/ingress-host.yaml

images:
  - name: my-playwright-tests
    newTag: v1-qa

configMapGenerator:
  - name: test-config
    literals:
      - ENVIRONMENT=qa
      - API_BASE_URL=https://api-qa.example.com
      - UI_BASE_URL=https://app-qa.example.com

# Changed from 'commonLabels' to 'labels'
labels:
  - pairs:
      environment: qa