apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playwright-qa

resources:
  - namespace.yaml
  - ../../base

# Use JSON patches instead
patches:
  - target:
      kind: CronJob
      name: playwright-ui-tests
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - target:
      kind: CronJob
      name: playwright-api-tests
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
  - path: patches/ingress-host.yaml

labels:
  - pairs:
      environment: qa