apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: playwright-qa-developer
  namespace: playwright-qa
rules:
  - apiGroups: ['', 'apps', 'batch']
    resources: ['pods', 'services', 'deployments', 'cronjobs', 'jobs']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch']
  - apiGroups: ['']
    resources: ['pods/log', 'pods/exec']
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: playwright-qa-developer-binding
  namespace: playwright-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: playwright-qa-developer
subjects:
  - kind: Group
    name: qa-developers
    apiGroup: rbac.authorization.k8s.io
