apiVersion: batch/v1
kind: CronJob
metadata:
  name: playwright-ui-tests
  labels:
    app: playwright-ui-tests
    test-type: ui
spec:
  schedule: '0 2 * * *' # Will be overridden per environment
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: playwright-ui-tests
            test-type: ui
        spec:
          restartPolicy: Never
          containers:
            - name: playwright-tests
              image: my-playwright-tests:v1 # Will be overridden per environment
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 9323
                  name: report-server
              command:
                - /bin/sh
                - -c
                - |
                  # Run Playwright UI tests
                  echo "[$(date)] Starting Playwright UI tests..."
                  npm run test:ui || TEST_FAILED=true

                  # Start report server
                  echo "[$(date)] Starting report server on port 9323..."
                  npx playwright show-report --port 9323 --host 0.0.0.0 &

                  # Keep pod running
                  echo "[$(date)] Report server running. Pod will stay alive for 5 minutes..."
                  sleep 300

                  # Exit with test status
                  echo "[$(date)] Shutting down..."
                  if [ "$TEST_FAILED" = "true" ]; then exit 1; fi
