apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob-api-tests.yaml
  - cronjob-ui-tests.yaml
  - deployment.yaml
  - playwright-api-reports-service.yaml
  - playwright-ui-reports-service.yaml
  - service.yaml
  - ingress.yaml

# Changed from 'commonLabels' to 'labels'
labels:
  - pairs:
      app.kubernetes.io/name: playwright-tests
      app.kubernetes.io/component: testing