apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob-api-tests.yaml
  - cronjob-ui-tests-europe.yaml
  - cronjob-ui-tests-india.yaml
  - cronjob-ui-tests-us.yaml
  - deployment.yaml
  - ingress.yaml
  - playwright-api-reports-service.yaml
  - playwright-ui-reports-service.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: playwright-tests
      app.kubernetes.io/component: testing